// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjnkdoleryjerjqkbdcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbmtkb2xlcnlqZXJqcWtiZGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTQzNzQsImV4cCI6MjA2MDAzMDM3NH0.2PsexdMLf4CpJJhvBDbcEHOwFJvQnaQBgKGp1vcdysg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);